feat(extension.ts): add mustache templates and generate api code files
alovajs/devtools pull request #3
Opened 2024-06-02 15:56 UTC by artneers

2024-06-03 02:18 UTC, JOU-amjs requested changes
总体来说逻辑理解我们应该是一致的，这块没问题，初步判定以下有三个比较大的问题：
1. 项目结构不清晰，现在主要还是在`extension.ts`中按步骤实现的，这样的问题是灵活性和可维护性较低，不利于后续的迭代，也可能你还没来得及整理，我的建议是先思考搭建架构，再以填代码的方式实现逻辑会更有效率。
2. 目前只实现了正常流程的逻辑，一些边缘情况的校验等还没有，这块缺失可能导致项目鲁棒性降低，如果还没来得及整理，建议也是实现逻辑的时候一并考虑进去。
3. 对typescript熟练度感觉需要提升一些，尽量标注上正确的类型，尽量不使用any或as xxx的方式，除非有些边缘情况要用到这些。

初步感觉目前还是demo阶段，还需要加把劲哦，建议可以按我上面的3点来修改一下，具体的我也在`code review`中给出了。

2024-06-03 02:18 UTC, JOU-amjs commented on src/extension.ts
> +      generateFile(distDir, 'apiDefinitions.js', renderApiDefinitions);
这里也不能直接写死，需要用一种方式来实现更灵活的方式，例如当你读取的是ts相关模板，就应该对应名称的`.ts`文件，这也是管理模板文件的一种方式。
例如你可以针对不同的文件创建一个类，这个类里包含了所有的内容，你只需要根据配置读取对应模板文件夹下的文件就好了，举例：
```ts
class TemplateFile {
  constructor(fileName: string, projectType: 'auto' | 'ts' | 'typescript' | 'module' | 'commonjs') {
    // 根据projectType确定使用哪个模板文件夹下的模板
    // 根据fileName确定当前类对应哪个文件，后缀由projectType确定
  }

  async outputFile(data: Record<string, any>, ouput: string) {
    // 这里实现模板文件渲染工作，例如返回文件内容和文件名，然后再写入output的文件夹
    
  }
}

// 使用
const apiDefinition = new TemplateFile('apiDefinition', config.type);
await apiDefinition.outputFile({ ... });
```

2024-06-03 11:57 UTC, MeetinaXD commented on src/utils/index.ts
> +  return new Promise((resolve, reject) => {
async/await 是一个语法糖，可以简便 Promise 的使用

有个小建议，如果使用了 async，就不需要手动返回一个 Promise 对象；当然也可以不写 async 关键字直接返回 Promise。我会更倾向于直接使用 async 😃

2024-06-03 12:31 UTC, MeetinaXD reviewed
😃 这也是我第一次认认真真来一次 review，也发现了一些自己的问题，收获不少。

加油！

2024-06-03 16:12 UTC, artneers commented on src/templates/apiDefinitions.mustache
> +export default {
ok，这个单独抽出来。

2024-06-03 16:21 UTC, artneers commented on src/utils/index.ts
> +const mustache = require('mustache');
ok，按照建议统一按import导入修改了。

2024-06-03 16:26 UTC, artneers commented on src/utils/index.ts
> +export async function readAndRenderTemplate(templatePath: any, view: any) {
> 在ts中不使用jsDoc的方式注释类型，建议直接在代码中使用类型，例如这边：
> 
> ```ts
> export async function readAndRenderTemplate(template: string, view: Record<string, any>) {
>   // ...
> }
> ```
> 
> 然后注释中的`{string}、{object}`等这些可以去掉

ok，后面都按照这个规范处理类型。

2024-06-03 16:28 UTC, artneers commented on src/utils/index.ts
> +export async function readAndRenderTemplate(templatePath: any, view: any) {
> jsDoc 可以在参数名后不带连字符（当然也可以带），但 VSCode 会将它连同后面的注释渲染为 Markdown 😢
> 
> <img alt="image" width="484" src="https://private-user-images.githubusercontent.com/40497962/336070756-359b9b7f-3297-49ab-a5e7-6661efe0cc16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzE5NDksIm5iZiI6MTcxNzQzMTY0OSwicGF0aCI6Ii80MDQ5Nzk2Mi8zMzYwNzA3NTYtMzU5YjliN2YtMzI5Ny00OWFiLWE1ZTctNjY2MWVmZTBjYzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE2MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMmJjMTk4NTg5ZDNkNjQ4MjU0OTRlM2IyZTQ4YWU5ODBmYjg3Njg5ZjcyYjY2MDBhNGU3MjJhMWI2Y2VmNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VEDjiJ954Iq6Ff3Ebm68Ipaog-Dpmjr7WoTwjHJ_mJk">
> 连字符在 jsDoc 中本意是增加可读性，但大部分编辑器现在都会将 jsDoc 中的变量名高亮，所以我觉得可以省掉这一步，直接在参数名后带注释，效果如下
> 
> <img alt="image" width="548" src="https://private-user-images.githubusercontent.com/40497962/336071737-e2ebc264-d3c2-46ee-9039-6140a5ff9d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzE5NDksIm5iZiI6MTcxNzQzMTY0OSwicGF0aCI6Ii80MDQ5Nzk2Mi8zMzYwNzE3MzctZTJlYmMyNjQtZDNjMi00NmVlLTkwMzktNjE0MGE1ZmY5ZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE2MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMTg2NDI3YTEwNDEwMTliZGQzODk4NWQ4MTY5ZDlkYThiMzgzMDEyNGM5OGMyMWViN2MwYWFmMjQ2MWQ2ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Usblq6ae68FUMbmhWcWlyx1D30SPGIlUUtK1S7nltzs">

![image](https://github.com/alovajs/devtools/assets/34784541/cbd8b587-5f89-436c-8629-2f75d8974964)
在window上 - 直接展示的，是不是mac上有兼容问题？

2024-06-03 16:36 UTC, artneers commented on src/extension.ts
> +
ok，直接采纳

2024-06-04 08:22 UTC, MeetinaXD commented on src/utils/index.ts
> +export async function readAndRenderTemplate(templatePath: any, view: any) {
应该不是兼容性问题，我没有讲清楚，抱歉。

在速览函数定义的时候（也就是你给出的截图）显示是正常的，但如果你在传入具体的某一个参数时（我给出的两个截图），vscode 会把 param 后面关于参数的 description 解析为 Markdown，也就把 `-` 解析为了一个无序列表项。

😢 讲道理这是合乎 jsdoc 规范的，应该只是 vscode 的渲染问题。不过在 alova 中，使用是不带连字符的风格。

我上面还漏了一个，`@return` 可以直接跟注释不需要加连字符（可以看一下你给出的截图，多了一个字符）

2024-06-04 14:28 UTC, artneers commented on src/utils/index.ts
> +export async function readAndRenderTemplate(templatePath: any, view: any) {
@MeetinaXD 理解了，我试了一下，确实是，已修改和alova保持一致

2024-06-04 16:12 UTC, artneers commented on src/extension.ts
> +      const data = await fetchData('https://generator3.swagger.io/openapi.json');
已按建议安装，并引入了OpenAPIV3。这个类型分别对应openapi的三个版本，记得开始设计的时候先考虑3.0，对吧？

2024-06-04 16:13 UTC, artneers commented on src/extension.ts
>    const myCommandId = 'alova.start';
已拆分为独立命令文件，并在extension.ts中注册

2024-06-04 16:14 UTC, artneers commented on src/extension.ts
> +
增加了config文件，存放可枚举的变量

2024-06-04 16:16 UTC, Owenmzz commented
目前待完成的还有：1、边缘情况 2、模版分类型读取

2024-06-05 09:18 UTC, JOU-amjs reviewed
灵活性和鲁棒性可以再提升一些，可以使用配置化是思路提升灵活性

2024-06-05 09:18 UTC, JOU-amjs commented on src/extension.ts
>    myStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
这里处理的不太好，myCommandId重复了，建议可以导出统一在extension.ts中注册命令：
```ts
// generateApi
export default {
  commandId: 'xxx',
  handler: async () => {...},
};
```

在`extension.ts`中：
```ts
import generateApi from './commands/generateApi';

const commands = [
  generateApi,
  // 下次有新的命令直接放这边就好
];
export function activate(context: vscode.ExtensionContext) {
  commands.forEach(({ commandId, handler }) => {
    context.subscriptions.push(vscode.commands.registerCommand(commandId, handler));
  });
}
```

2024-06-05 09:18 UTC, JOU-amjs commented on src/commands/generateApi.ts
> +    const commentText = await readAndRenderTemplate(path.resolve(__dirname, '../../src/templates/comment.mustache'), {
这边以下的生成代码部分，建议也可以使用配置化的方式处理，可能更加优雅些，示例：
```ts
const templeFiles = [
  {
    fileName: 'comment',
    injections: () => data
  },
  {
    fileName: 'index',
    injections: () => ({
      ...data,
      [frameTag]: true
    }),
    // 其他文件配置...
  }
]

const suffix = '...'; // 后缀根据项目类型来判断
// 然后循环就好了
templeFiles.forEach(async ({ fileName, injections }) => {
  const renderedContent = await readAndRenderTemplate(
    path.resolve(__dirname, `../../src/templates/${fileName}.mustache`),
    injections()
  );
  generateFile(distDir, `${fileName}.${suffix}`, renderedContent);
});
```

2024-06-05 14:11 UTC, artneers commented on src/config/index.ts
> +export const frameworkName: string[] = ['vue', 'react'];
好的

2024-06-05 14:13 UTC, artneers commented on design/apiDefinitions.js
> +/// <reference path="./globals.d.ts1" />
ok，可忽略，这块是误操作，确认了模版中是.ts后缀

2024-06-05 14:15 UTC, artneers commented on src/commands/generateApi.ts
> +    const frameTag = frameworkName.find(framework => packageJson.dependencies[framework]) || 'vue';
那就不能设置默认值了，直接去掉后面或的'vue‘。目前statesHook的逻辑是符合哪个框架生成哪个Hook。

2024-06-05 14:17 UTC, artneers commented on src/commands/generateApi.ts
> +    const distDir = path.join(__dirname, '../../design');
还没改，待完成项

2024-06-05 14:18 UTC, artneers commented on src/commands/generateApi.ts
> +    if (!data.paths) return;
ok，这个会统一放在边缘情况中处理，我先梳理流程图，最后再改

2024-06-05 14:19 UTC, artneers commented on src/commands/generateApi.ts
> +import { frameworkName } from '../config/index';
直接合一下内容，按保留这个src/globalConfig.ts处理吧

2024-06-05 14:19 UTC, artneers commented on src/utils/index.ts
> +    const data = await fs.readFileSync(templatePath, 'utf-8');
ok，这块应该改为异步。

2024-06-05 14:22 UTC, artneers commented on src/extension.ts
>    myStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
明白了。而且这块还有个想法，可以在此基础上，增加一个插件化注册函数，类似于app.use(插件)的方式，这样每次有插件新增，直接在外侧新增调用代码，不需要改动原来的代码。

2024-06-05 14:49 UTC, artneers commented on src/commands/generateApi.ts
> +    const commentText = await readAndRenderTemplate(path.resolve(__dirname, '../../src/templates/comment.mustache'), {
ok，这部分我再调整一下

2024-06-07 14:51 UTC, artneers commented on src/extension.ts
> +      generateFile(distDir, 'apiDefinitions.js', renderApiDefinitions);
已修改完成，注释部分的模板内容是在遍历4个模版文件之前完成的，所以还需要手动渲染一遍，没有想到更好的办法。

2024-06-13 04:12 UTC, merged